"""cnpj em respostas

Revision ID: 63a3bcd09331
Revises: 239asd9acas
Create Date: 2025-10-28 19:26:16.409295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a3bcd09331'
down_revision: Union[str, Sequence[str], None] = '239asd9acas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('respostas', 'cnpj',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=18),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('respostas', 'cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)
    # ### end Alembic commands ###
