"""descricao em perguntas

Revision ID: 9f2092ac8cc1
Revises: 63a3bcd09331
Create Date: 2025-11-04 12:47:21.302489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2092ac8cc1'
down_revision: Union[str, Sequence[str], None] = '63a3bcd09331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perguntas', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perguntas', 'descricao')
    # ### end Alembic commands ###
