"""fazendo relacionamento de opcao

Revision ID: a6d3812c8a16
Revises: bd8179de1a09
Create Date: 2025-08-28 16:41:00.395640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d3812c8a16'
down_revision: Union[str, Sequence[str], None] = 'bd8179de1a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'respostas_itens', 'opcoes', ['valor_opcao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'respostas_itens', type_='foreignkey')
    # ### end Alembic commands ###
