"""add personalizavel em opcaoes

Revision ID: c07586b7ae5c
Revises: 9f2092ac8cc1
Create Date: 2025-11-05 14:15:25.127116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07586b7ae5c'
down_revision: Union[str, Sequence[str], None] = '9f2092ac8cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opcoes', sa.Column('personalizavel', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('opcoes', 'personalizavel', server_default=None)
    op.execute("ALTER TYPE tipo_pergunta ADD VALUE IF NOT EXISTS 'multipla_escolha_personalizada'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opcoes', 'personalizavel')
    # ### end Alembic commands ###
