"""integracoes genericas

Revision ID: c6b257f48808
Revises: 1c2c799555f4
Create Date: 2025-10-01 19:38:42.214559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6b257f48808'
down_revision: Union[str, Sequence[str], None] = '1c2c799555f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integracoes_id'), table_name='integracoes')
    op.drop_table('integracoes')
    op.drop_index(op.f('ix_ixc_integracoes_id'), table_name='ixc_integracoes')
    op.drop_table('ixc_integracoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ixc_integracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('porta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('nome_banco', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('habilitada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ixc_integracoes')),
    sa.UniqueConstraint('endereco', 'nome_banco', name=op.f('uix_endereco_nome_banco'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ixc_integracoes_id'), 'ixc_integracoes', ['id'], unique=False)
    op.create_table('integracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('habilitada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integracoes'))
    )
    op.create_index(op.f('ix_integracoes_id'), 'integracoes', ['id'], unique=False)
    # ### end Alembic commands ###
