"""adcionando cpf

Revision ID: d25feab1557d
Revises: 790fb0f81730
Create Date: 2025-09-23 18:56:45.264594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd25feab1557d'
down_revision: Union[str, Sequence[str], None] = '790fb0f81730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.create_index('ux_respostas_form_cpf_partial', 'respostas', ['formulario_id', 'cpf'], unique=True, postgresql_where=sa.text('cpf IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_respostas_form_cpf_partial', table_name='respostas', postgresql_where=sa.text('cpf IS NOT NULL'))
    op.drop_column('respostas', 'cpf')
    op.create_table('ixc_integracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('porta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('nome_banco', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('habilitada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ixc_integracoes_pkey')),
    sa.UniqueConstraint('endereco', 'nome_banco', name=op.f('uix_endereco_nome_banco'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ixc_integracoes_id'), 'ixc_integracoes', ['id'], unique=False)
    # ### end Alembic commands ###
